services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1

  backend_test:
    build: ./backend
    container_name: backend_test
    depends_on:
      - backend
    command: >
      sh -c "sleep 5 && python test_core.py"
    restart: "no"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      backend_test:
        condition: service_completed_successfully

volumes:
  backend_data:
