services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

volumes:
  backend_data:
